### ISSUE TITLE
Some problems about discarding auxiliary branches during inference?

### ISSUE THREAD

**Issue by ReverseSystem001** [d-li14/DHM#2]
thanks for the amazing paper. the git said : while no computatonal overheads are introduced after discarding those auxiliary branches during inference.
do you mean we can pick out the  corresponding weights(main branch) from the trained weight??? 
Hope your replay! Thanks

**Comment by d-li14** [comment]
Yes, you could pick out the main branch weights for inference. You should also load it to a pytorch official [ResNet model](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py) instead of the [multi-branch network](https://github.com/d-li14/DHM/blob/master/models/imagenet/resnet.py) in this repo.

**Comment by ReverseSystem001** [comment]
thanks. Does the paper performance evaluate only by the main branch?

**Comment by d-li14** [comment]
Sure.

**Comment by ReverseSystem001** [comment]
get , thanks.
